version : '3.8'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  goapp1:
    image: goapp
    environment:
      - APPID=1
      - PORT=1111
  goapp2:
    image: goapp
    environment:
      - APPID=2
      - PORT=2222
  goapp3:
    image: goapp
    environment:
      - APPID=3
      - PORT=3333
  goapp4:
    image: goapp
    environment:
      - APPID=4
      - PORT=4444
